version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: pg18-dev
    restart: unless-stopped

    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./volumes/pg:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d devdb -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

